// ─── 📚 DATABASE KATA & TEMA UNDERCOVER (1000+ KATA & RATUSAN PASANGAN KATA) ───
// Berisi ratusan pasangan kata natural bahasa Indonesia lintas kategori populer.

export const THEMES = {
  KULINER: { label: '🍜 Kuliner & Jajanan', desc: 'Makanan, minuman, jajanan pasar, bumbu dapur & resto' },
  GAMING: { label: '🎮 Gaming & Pop Culture', desc: 'Game, anime, manga, film, musik, tontonan & superhero' },
  SOSIAL: { label: '🏠 Kehidupan & Budaya Modern', desc: 'Kosan, asmara, kantor, medsos, aplikasi & jalanan' },
  ALAM: { label: '🐾 Alam, Profesi, Gadget & Benda', desc: 'Hewan, pekerjaan, tempat wisata, fashion & barang harian' }
};

export const THEME_KEYS = Object.keys(THEMES);

export const WORD_PAIRS = [
  // ════════════════════════════════════════════════════════════════════
  // 🍜 KULINER, JAJANAN, MAKANAN & MINUMAN (THEME: KULINER)
  // ════════════════════════════════════════════════════════════════════
  // Olahan Mie & Pasta
  { civilian: 'INDOMIE', undercover: 'MIE SEDAAP', category: '🍜 Kuliner / Mie Instan', theme: 'KULINER' },
  { civilian: 'MIE GACOAN', undercover: 'MIE JEBEW', category: '🌶️ Kuliner Mie Pedas', theme: 'KULINER' },
  { civilian: 'MIE AYAM', undercover: 'BAKSO SAPI', category: '🍲 Makanan Kuah Gerobak', theme: 'KULINER' },
  { civilian: 'SPAGHETTI', undercover: 'FETTUCCINE', category: '🍝 Pasta Khas Italia', theme: 'KULINER' },
  { civilian: 'KWETIAW GORENG', undercover: 'BIHUN GORENG', category: '🥢 Olahan Mie Tepung', theme: 'KULINER' },
  { civilian: 'MIE ACEH', undercover: 'MIE GORENG JAWA', category: '🍜 Olahan Mie Nusantara', theme: 'KULINER' },
  { civilian: 'INDOMIE GORENG', undercover: 'INDOMIE KUAH', category: '🍜 Varian Rasa Indomie', theme: 'KULINER' },
  { civilian: 'RAMEN JEPANG', undercover: 'UDON KUAH', category: '🍜 Mie Khas Jepang', theme: 'KULINER' },
  { civilian: 'MIE DOK-DOK', undercover: 'MIE TEK-TEK', category: '🍳 Mie Masak Malam', theme: 'KULINER' },
  { civilian: 'MIE SEDAAP KOREAN SPICY', undercover: 'SAMYANG RAMYUN', category: '🌶️ Mie Pedas Korea', theme: 'KULINER' },
  { civilian: 'SOHUN', undercover: 'BIHUN', category: '🥢 Olahan Mie Putih', theme: 'KULINER' },
  { civilian: 'MIE KOCOK BANDUNG', undercover: 'MIE CELOR PALEMBANG', category: '🍲 Mie Tradisional Kuah Kental', theme: 'KULINER' },
  { civilian: 'PASTA CARBONARA', undercover: 'PASTA BOLOGNESE', category: '🍝 Saus Pasta Western', theme: 'KULINER' },
  { civilian: 'MIE ONGKLOK', undercover: 'MIE TITI', category: '🍜 Kuliner Mie Khas Daerah', theme: 'KULINER' },

  // Olahan Nasi & Beras
  { civilian: 'NASI PADANG', undercover: 'NASI UDUK', category: '🍛 Menu Nasi Populer', theme: 'KULINER' },
  { civilian: 'NASI GORENG', undercover: 'NASI KEBULI', category: '🍚 Nasi Olahan Bumbu', theme: 'KULINER' },
  { civilian: 'NASI KUNING', undercover: 'NASI LIWET', category: '🍚 Nasi Tradisional Gurih', theme: 'KULINER' },
  { civilian: 'BUBUR AYAM', undercover: 'LONTONG SAYUR', category: '🥣 Sarapan Pagi Berkuah', theme: 'KULINER' },
  { civilian: 'NASI KUCING ANGKRICAN', undercover: 'ONIGIRI NASI KEPAL', category: '🍙 Nasi Porsi Mini Bungkus', theme: 'KULINER' },
  { civilian: 'NASI GILA', undercover: 'NASI RUWET MAGELANGAN', category: '🍳 Nasi Goreng Aneka Topping', theme: 'KULINER' },
  { civilian: 'KETUPAT LEBARAN', undercover: 'LONTONG PLASTIK', category: '🥢 Olahan Beras Bungkus Padat', theme: 'KULINER' },
  { civilian: 'NASI BEBEK MADURA', undercover: 'AYAM PENYET SURABAYA', category: '🍗 Nasi Sambal Kaki Lima', theme: 'KULINER' },
  { civilian: 'NASI TUTUG ONCOM', undercover: 'NASI TIMBEL SUNDA', category: '🍚 Nasi Tradisional Khas Sunda', theme: 'KULINER' },
  { civilian: 'NASI HAINAN', undercover: 'NASI BRIYANI', category: '🍚 Nasi Rempah Khas Mancanegara', theme: 'KULINER' },
  { civilian: 'BUBUR KACANG IJO', undercover: 'BUBUR KETAN HITAM', category: '🥣 Bubur Manis Santan', theme: 'KULINER' },
  { civilian: 'BUBUR SUMSUM', undercover: 'BUBUR CANDIL', category: '🥣 Jajanan Manis Kuah Gula Merah', theme: 'KULINER' },
  { civilian: 'NASI TIM AYAM', undercover: 'BUBUR AYAM CINA', category: '🥣 Olahan Nasi Lembut Hangat', theme: 'KULINER' },
  { civilian: 'NASI MEGONO', undercover: 'NASI GANDUL', category: '🍛 Kuliner Nasi Khas Jawa Tengah', theme: 'KULINER' },

  // Olahan Daging, Ayam & Seafood
  { civilian: 'RENDANG DAGING', undercover: 'GULAI SAPI', category: '🥘 Masakan Minang Santan', theme: 'KULINER' },
  { civilian: 'RAWON SURABAYA', undercover: 'SOTO DAGING MADURA', category: '🍲 Sup Daging Tradisional', theme: 'KULINER' },
  { civilian: 'SATE AYAM MADURA', undercover: 'SATE DAGING PADANG', category: '🍢 Kuliner Sate Bumbu Khas', theme: 'KULINER' },
  { civilian: 'SATE TAICHAN', undercover: 'SATE LILIT BALI', category: '🍢 Olahan Sate Tanpa Kacang', theme: 'KULINER' },
  { civilian: 'AYAM GEPREK', undercover: 'AYAM PENYET', category: '🍗 Ayam Sambal Ulek Pedas', theme: 'KULINER' },
  { civilian: 'AYAM GORENG LENGKUAS', undercover: 'AYAM BAKAR TALIWANG', category: '🍗 Olahan Ayam Tradisional', theme: 'KULINER' },
  { civilian: 'BEBEK GORENG CRISPY', undercover: 'PECEL LELE LAMONGAN', category: '🍱 Menu Warung Tenda Malam', theme: 'KULINER' },
  { civilian: 'SOP IGA SAPI', undercover: 'SOP BUNTUT', category: '🍲 Sup Daging Tulang Sapi', theme: 'KULINER' },
  { civilian: 'GULE KAMBING', undercover: 'TONGSENG KAMBING', category: '🍲 Masakan Daging Kambing', theme: 'KULINER' },
  { civilian: 'SE\'I SAPI KUPANG', undercover: 'DENDENG BALADO BASAH', category: '🥩 Olahan Daging Asap / Kering', theme: 'KULINER' },
  { civilian: 'NUGGET AYAM', undercover: 'SOSIS SAPI', category: '🌭 Olahan Frozen Food Praktis', theme: 'KULINER' },
  { civilian: 'KORNET DAGING', undercover: 'ABON SAPI', category: '🥫 Olahan Daging Awetan', theme: 'KULINER' },
  { civilian: 'STEAK SIRLOIN', undercover: 'STEAK TENDERLOIN', category: '🥩 Bagian Potongan Daging Steak', theme: 'KULINER' },
  { civilian: 'BULGOGI DAGING', undercover: 'YAKINIKU JEPANG', category: '🥩 Daging Panggang Saus Asia', theme: 'KULINER' },
  { civilian: 'GURAME ASAM MANIS', undercover: 'NILA BAKAR KECAP', category: '🐟 Olahan Ikan Air Tawar', theme: 'KULINER' },
  { civilian: 'CUMI GORENG TEPUNG', undercover: 'UDANG SAUS PADANG', category: '🦐 Olahan Makanan Laut (Seafood)', theme: 'KULINER' },
  { civilian: 'KEPITING SAUS TIRAM', undercover: 'LOBSTER PANGGANG', category: '🦀 Seafood Bercangkang Mewah', theme: 'KULINER' },
  { civilian: 'KERANG DARA REBUS', undercover: 'KERANG HIJAU SAUS PADANG', category: '🦪 Jajanan Kerang Rebus', theme: 'KULINER' },
  { civilian: 'EMPAP GENTONG', undercover: 'COTO MAKASSAR', category: '🍲 Sup Daging Kuah Santan Jeroan', theme: 'KULINER' },
  { civilian: 'SOTO BETAWI', undercover: 'SOTO MIE BOGOR', category: '🍜 Kuliner Soto Berkuah Khas', theme: 'KULINER' },

  // Jajanan Kaki Lima, Gorengan & Street Food
  { civilian: 'TAHU BULAT', undercover: 'CIRENG BUMBU RUJAK', category: '🥟 Jajanan Gorengan Gurih', theme: 'KULINER' },
  { civilian: 'BATAGOR BANDUNG', undercover: 'SIOMAY IKAN', category: '🥟 Jajanan Saus Bumbu Kacang', theme: 'KULINER' },
  { civilian: 'MARTABAK TELUR', undercover: 'MARTABAK MANIS', category: '🥞 Menu Gerobak Martabak', theme: 'KULINER' },
  { civilian: 'PISANG GORENG CRISPY', undercover: 'ROTI BAKAR BANDUNG', category: '🍞 Camilan Warkop Malam', theme: 'KULINER' },
  { civilian: 'CILOK KUAH', undercover: 'CIMOL BUMBU TABUR', category: '🍡 Jajanan Olahan Tepung Kanji', theme: 'KULINER' },
  { civilian: 'SEBLAK CEKER', undercover: 'BASO ACI TULANG RANGU', category: '🌶️ Kuliner Pedas Khas Bandung', theme: 'KULINER' },
  { civilian: 'PEMPEK KAPAL SELAM', undercover: 'PEMPEK LENJER', category: '🐟 Olahan Ikan Khas Palembang', theme: 'KULINER' },
  { civilian: 'TELUR GULUNG SD', undercover: 'CILUNG (ACI GULUNG)', category: '🍳 Jajanan Favorit Depan SD', theme: 'KULINER' },
  { civilian: 'BAKWAN SAYUR', undercover: 'TEMPE MENDOAN', category: '🍤 Gorengan Gurih Tepung', theme: 'KULINER' },
  { civilian: 'PANGSIT GORENG', undercover: 'DIMSUM AYAM KUKUS', category: '🥟 Camilan Kukus & Goreng Renyah', theme: 'KULINER' },
  { civilian: 'KROKET KENTANG', undercover: 'RISOL MAYO SMOKED BEEF', category: '🥐 Gorengan Tepung Panir Isi', theme: 'KULINER' },
  { civilian: 'JASUKE (JAGUNG KEJU)', undercover: 'JAGUNG BAKAR PEDAS', category: '🌽 Olahan Jagung Manis Hangat', theme: 'KULINER' },
  { civilian: 'TAHU GEJROT CIREBON', undercover: 'TAHU WALIK BANYUWANGI', category: '🥢 Camilan Olahan Tahu Gurih', theme: 'KULINER' },
  { civilian: 'LUMPIA BASAH BANDUNG', undercover: 'LUMPIA GORENG SEMARANG', category: '🌯 Olahan Lumpia Rebung', theme: 'KULINER' },
  { civilian: 'ODENG KUAH', undercover: 'TTEOKBOKKI PEDAS', category: '🍢 Jajanan Street Food Korea', theme: 'KULINER' },
  { civilian: 'FRENCH FRIES', undercover: 'KERIPIK SINGKONG BALADO', category: '🍟 Camilan Renyah Asin Gurih', theme: 'KULINER' },
  { civilian: 'CREPES CRUNCHY', undercover: 'KUE LEKKER KAMPUNG', category: '🥞 Camilan Tipis Renyah Manis', theme: 'KULINER' },
  { civilian: 'TAKOYAKI JEPANG', undercover: 'OKONOMIYAKI', category: '🐙 Makanan Khas Jepang Gurih', theme: 'KULINER' },
  { civilian: 'CORNDOG MOZZARELLA', undercover: 'HOTDOG SOSIS', category: '🌭 Olahan Sosis & Keju Balut Tepung', theme: 'KULINER' },
  { civilian: 'KENTANG SPIRAL', undercover: 'CURLY FRIES', category: '🍟 Variasi Kentang Goreng Unik', theme: 'KULINER' },
  { civilian: 'TAHU BAKSO', undercover: 'OTAK-OTAK BAKAR', category: '🍢 Camilan Gurih Bumbu Cocol', theme: 'KULINER' },
  { civilian: 'ASINAN BOGOR', undercover: 'RUJAK BUAH ULEK', category: '🥗 Olahan Buah Bumbu Segar Pedas', theme: 'KULINER' },
  { civilian: 'KERAK TELOR BETAWI', undercover: 'SURABI ONCOM BANDUNG', category: '🍳 Jajanan Tradisional Panggang', theme: 'KULINER' },
  { civilian: 'KUE PANCONG LUMER', undercover: 'KUE BANDROS KELAPA', category: '🥞 Kue Tradisional Cetakan Besi', theme: 'KULINER' },
  { civilian: 'PENTOL BAKAR', undercover: 'CILOK GOANG PEDAS', category: '🍡 Jajanan Bakso Tusuk Pinggir Jalan', theme: 'KULINER' },

  // Restoran, Fast Food & Brand Kuliner
  { civilian: 'PIZZA HUT', undercover: 'DOMINO\'S PIZZA', category: '🍕 Gerai Waralaba Pizza', theme: 'KULINER' },
  { civilian: 'KFC (KENTUCKY FRIED CHICKEN)', undercover: 'RICHEESE FACTORY', category: '🍗 Restoran Cepat Saji Ayam', theme: 'KULINER' },
  { civilian: 'MCDONALD\'S (MCD)', undercover: 'BURGER KING', category: '🍔 Waralaba Burger & Kentang', theme: 'KULINER' },
  { civilian: 'SUBWAY SANDWICH', undercover: 'KEBAB BABA RAFI', category: '🥪 Roti Lapis Gulung Isi Daging', theme: 'KULINER' },
  { civilian: 'DONAT J.CO', undercover: 'DUNKIN\' DONUTS', category: '🍩 Brand Gerai Donat Ternama', theme: 'KULINER' },
  { civilian: 'HOKBEN (HOKA HOKA BENTO)', undercover: 'YOSHINOYA JAPANESE BEEF', category: '🍱 Restoran Cepat Saji Jepang', theme: 'KULINER' },
  { civilian: 'WAROENG STEAK & SHAKE', undercover: 'STEAK 21', category: '🥩 Restoran Daging Steak', theme: 'KULINER' },
  { civilian: 'A&W RESTAURANT', undercover: 'TEXAS CHICKEN', category: '🍗 Restoran Cepat Saji Ayam & Soda', theme: 'KULINER' },
  { civilian: 'SOLARIA', undercover: 'D\'COST SEAFOOD', category: '🍽️ Restoran Keluarga Populer Mall', theme: 'KULINER' },
  { civilian: 'SUSHI TEI', undercover: 'ICHIBAN SUSHI', category: '🍣 Restoran Makanan Khas Jepang', theme: 'KULINER' },
  { civilian: 'PEPPER LUNCH', undercover: 'KIMUKATSU', category: '🥩 Restoran Hotplate & Katsu', theme: 'KULINER' },
  { civilian: 'MARUGAME UDON', undercover: 'GOKANA RAMEN & TEPPAN', category: '🍜 Restoran Mie & Bento Jepang', theme: 'KULINER' },
  { civilian: 'BAKMI GM', undercover: 'TA WAN CHINESE FOOD', category: '🥢 Restoran Masakan Oriental', theme: 'KULINER' },
  { civilian: 'CHATIME', undercover: 'KOI THE', category: '🧋 Gerai Minuman Boba Milk Tea', theme: 'KULINER' },
  { civilian: 'MIXUE ICE CREAM', undercover: 'MOMOYO ICE CREAM', category: '🍦 Gerai Es Krim & Teh Murah', theme: 'KULINER' },
  { civilian: 'STARBUCKS COFFEE', undercover: 'KOPI KENANGAN', category: '☕ Brand Kedai Kopi Populer', theme: 'KULINER' },
  { civilian: 'JANJI JIWA', undercover: 'POINT COFFEE INDOMARET', category: '☕ Kedai Kopi Susu Praktis', theme: 'KULINER' },
  { civilian: 'WARTEG KHARISMA BAHARI', undercover: 'RUMAH MAKAN PADANG SEDERHANA', category: '🍽️ Tempat Makan Murah Meriah', theme: 'KULINER' },

  // Minuman & Segar-segar
  { civilian: 'KOPI SUSU GULA AREN', undercover: 'BOBA MILK TEA', category: '🧋 Minuman Manis Kekinian', theme: 'KULINER' },
  { civilian: 'ES TEH MANIS JUMBO', undercover: 'ES JERUK PERAS', category: '🍹 Minuman Segar Warung', theme: 'KULINER' },
  { civilian: 'ES CENDOL DURIAN', undercover: 'ES DAWET AYU BANJARNEGARA', category: '🍧 Minuman Tradisional Santan', theme: 'KULINER' },
  { civilian: 'ES KELAPA MUDA', undercover: 'ES DEGAN JERUK', category: '🥥 Minuman Segar Pelepas Dahaga', theme: 'KULINER' },
  { civilian: 'KOPI HITAM TUBRUK', undercover: 'ESPRESSO SHOT', category: '☕ Olahan Kopi Murni Pekat', theme: 'KULINER' },
  { civilian: 'CAPPUCCINO', undercover: 'CAFE LATTE', category: '☕ Menu Kopi Berbusa Susu', theme: 'KULINER' },
  { civilian: 'MATCHA GREEN TEA LATTE', undercover: 'THAI MILK TEA', category: '🍵 Minuman Teh Rasa Khas Asia', theme: 'KULINER' },
  { civilian: 'ES CAMPUR SARI', undercover: 'ES TELER NANGKA ALPUKAT', category: '🍧 Es Aneka Isian Buah Manis', theme: 'KULINER' },
  { civilian: 'JUS ALPUKAT KENTAL', undercover: 'JUS MANGGA HARUM MANIS', category: '🥤 Olahan Jus Buah Segar', theme: 'KULINER' },
  { civilian: 'AQUA GALON', undercover: 'LE MINERALE BOTOL', category: '💧 Air Mineral Kemasan Rumah', theme: 'KULINER' },
  { civilian: 'TEH BOTOL SOSRO', undercover: 'TEH PUCUK HARUM', category: '🧃 Minuman Teh Kemasan Populer', theme: 'KULINER' },
  { civilian: 'POCARI SWEAT', undercover: 'ISOPLUS ELEKTROLIT', category: '⚡ Minuman Isotonik Olahraga', theme: 'KULINER' },
  { civilian: 'BEAR BRAND (SUSU BERUANG)', undercover: 'ULTRA MILK COKELAT', category: '🥛 Susu Segar Kemasan Kaleng/Kotak', theme: 'KULINER' },
  { civilian: 'ES KUWUD BALI', undercover: 'ES DOGER KELAPA', category: '🍧 Minuman Dingin Es Tradisional', theme: 'KULINER' },
  { civilian: 'WEDANG RONDE JAHE', undercover: 'SEKOTENG HANGAT', category: '🍵 Minuman Hangat Jahe Kacang', theme: 'KULINER' },
  { civilian: 'BAJIGUR SANTAN', undercover: 'BANDREK JAHE PEDAS', category: '🥥 Minuman Hangat Tradisional Sunda', theme: 'KULINER' },
  { civilian: 'SUSU KEDELAI MURNI', undercover: 'SUSU OATMILK / ALMOND', category: '🥛 Minuman Susu Nabati Sehat', theme: 'KULINER' },
  { civilian: 'YOGURT DRINK CIMORY', undercover: 'YAKULT PROBIOTIK', category: '🍶 Minuman Fermentasi Baik Pencernaan', theme: 'KULINER' },
  { civilian: 'COCA-COLA BOTOL', undercover: 'PEPSI BIRU', category: '🥤 Minuman Soda Berkarbonasi Hitam', theme: 'KULINER' },
  { civilian: 'FANTA MERAH STROBERI', undercover: 'SPRITE LEMON JERUK NIPIS', category: '🥤 Minuman Soda Rasa Buah', theme: 'KULINER' },
  { civilian: 'KRATINGDAENG BOTOL KACA', undercover: 'EXTRA JOSS SERBUK', category: '⚡ Minuman Penambah Energi', theme: 'KULINER' },
  { civilian: 'ES CINCAU HIJAU SANTAN', undercover: 'ES CINCAU HITAM CAPPUCCINO', category: '🍧 Minuman Isian Cincau Segar', theme: 'KULINER' },
  { civilian: 'SIRUP MARJAN COCO PANDAN', undercover: 'SIRUP ABC JERUK', category: '🍹 Sirup Manis Spesial Buka Puasa', theme: 'KULINER' },

  // Buah, Sayur, Rempah & Bahan Dapur
  { civilian: 'BUAH DURIAN MONTONG', undercover: 'BUAH NANGKA MATANG', category: '🍈 Buah Tropis Beraroma Tajam', theme: 'KULINER' },
  { civilian: 'SEMANGKA MERAH TANPA BIJI', undercover: 'MELON HIJAU SEGAR', category: '🍉 Buah Berair Manis Pelepas Dahaga', theme: 'KULINER' },
  { civilian: 'APEL FUJI MERAH', undercover: 'BUAH PIR KUNING', category: '🍎 Buah Renyah Berdaging Putih', theme: 'KULINER' },
  { civilian: 'MANGGA HARUM MANIS', undercover: 'MANGGA GEDONG GINCU', category: '🥭 Varian Buah Mangga Manis', theme: 'KULINER' },
  { civilian: 'JERUK BALI RAKSASA', undercover: 'JERUK NIPIS KECIL', category: '🍊 Keluarga Buah Jeruk Sitrun', theme: 'KULINER' },
  { civilian: 'CABAI RAWIT MERAH', undercover: 'CABAI MERAH KERITING', category: '🌶️ Bumbu Dapur Pemicu Pedas', theme: 'KULINER' },
  { civilian: 'BAWANG MERAH BREBES', undercover: 'BAWANG PUTIH TUNGGAL', category: '🧄 Bumbu Dasar Penyedap Masakan', theme: 'KULINER' },
  { civilian: 'LENGKUAS LAOS', undercover: 'JAHE EMPRIT MERAH', category: '🫚 Rimpang Rempah Tradisional', theme: 'KULINER' },
  { civilian: 'KUNYIT KUNING', undercover: 'KENCUR AROMATIK', category: '🫚 Rempah Bumbu Jamu & Seblak', theme: 'KULINER' },
  { civilian: 'KECAP MANIS BANGO', undercover: 'SAUS TIRAM SAORI', category: '🥣 Penyedap Masakan Tumisan', theme: 'KULINER' },
  { civilian: 'SAMBAL TERASI ULEK', undercover: 'SAMBAL MATAH BALI', category: '🌶️ Sambal Pelengkap Lauk Nasi', theme: 'KULINER' },
  { civilian: 'SAYUR KANGKUNG TUMIS', undercover: 'SAYUR BAYAM BENING', category: '🥬 Sayuran Hijau Favorit Rumah', theme: 'KULINER' },
  { civilian: 'WORTEL SAYUR SOP', undercover: 'KENTANG BULAT', category: '🥕 Sayuran Bahan Sup Dapur', theme: 'KULINER' },
  { civilian: 'BROKOLI HIJAU', undercover: 'KEMBANG KOL PUTIH', category: '🥦 Sayuran Berbunga Sehat', theme: 'KULINER' },
  { civilian: 'PETAI GORENG', undercover: 'JENGKOL BALADO', category: '🧆 Lalapan Tradisional Beraroma Khas', theme: 'KULINER' },
  { civilian: 'KUBIS / KOL GORENG', undercover: 'SELADA AIR MENTAH', category: '🥗 Sayuran Pendamping Sambal Pecel', theme: 'KULINER' },
  { civilian: 'MENTIMUN SEGAR', undercover: 'TERONG UNGU BALADO', category: '🥒 Buah Sayur Pelengkap Lauk', theme: 'KULINER' },
  { civilian: 'TERASI UDANG JUWANA', undercover: 'PETIS IKAN SIDOARJO', category: '🦐 Pasta Bumbu Fermentasi Gurih', theme: 'KULINER' },
  { civilian: 'MINYAK GORENG SAWIT', undercover: 'MENTEGA / MARGARIN BLUE BAND', category: '🧈 Bahan Dasar Menggoreng Makanan', theme: 'KULINER' },
  { civilian: 'GARAM DAPUR BERYODIUM', undercover: 'MICIN PENYEDAP (MSG)', category: '🧂 Bumbu Penyedap Rasa Makanan', theme: 'KULINER' },
  { civilian: 'GULA PASIR TEBU', undercover: 'GULA MERAH JAWA (AREN)', category: '🍯 Pemanis Alami Masakan', theme: 'KULINER' },
  { civilian: 'SANTAN KELAPA PERAS', undercover: 'SUSU EVAPORASI KENTAL', category: '🥥 Cairan Gurih Kental Masakan', theme: 'KULINER' },
  { civilian: 'MAYONAIS CREAMY', undercover: 'SAUS MUSTARD KUNING', category: '🥪 Saus Pelengkap Salad & Burger', theme: 'KULINER' },
  { civilian: 'WASABI PEDAS MENYENGAT', undercover: 'SAMBAL KECAP RAWIT', category: '🍣 Saus Cocolan Makanan', theme: 'KULINER' },

  // Kue, Camilan & Dessert
  { civilian: 'BROWNIES KUKUS AMANDA', undercover: 'KUE BOLU PANGGANG', category: '🍰 Kue Lembut Manis Cokelat', theme: 'KULINER' },
  { civilian: 'CHEESECAKE LUMER', undercover: 'TIRAMISU CAFE', category: '🧀 Kue Penutup Lembut Mewah', theme: 'KULINER' },
  { civilian: 'KLEPON GULA MERAH', undercover: 'ONDE-ONDE WIJEN KACANG HIJAU', category: '🍡 Jajanan Pasar Isi Manis', theme: 'KULINER' },
  { civilian: 'LAPIS LEGIT KAYA REMPAH', undercover: 'KUE BIKA AMBON MEDAN', category: '🍰 Kue Tradisional Khas Hari Raya', theme: 'KULINER' },
  { civilian: 'DONAT GULA SALJU', undercover: 'ROTI CANAI SUSU', category: '🍩 Camilan Tepung Manis', theme: 'KULINER' },
  { civilian: 'KASTENGEL KEJU RENYAH', undercover: 'KUE NASTAR SELAI NANAS', category: '🍍 Kue Kering Lebaran', theme: 'KULINER' },
  { civilian: 'PUTRI SALJU DINGIN', undercover: 'KUE LIDAH KUCING CRUNCHY', category: '🍪 Kue Kering Renyah Manis', theme: 'KULINER' },
  { civilian: 'WAFFLE ICE CREAM', undercover: 'PANCAKE SIRUP MAPLE', category: '🥞 Sarapan Manis Topping Mewah', theme: 'KULINER' },
  { civilian: 'CHURROS COKELAT SPANYOL', undercover: 'DONAT KENTANG EMPUK', category: '🥖 Camilan Goreng Tabur Gula Halus', theme: 'KULINER' },
  { civilian: 'ES PISANG IJO MAKASSAR', undercover: 'PISANG EPE SAUS GULA MERAH', category: '🍌 Olahan Pisang Khas Sulawesi', theme: 'KULINER' },
  { civilian: 'KUE APEM KUKUS', undercover: 'KUE CUCUR GULA MERAH', category: '🍘 Jajanan Pasar Tradisional Manis', theme: 'KULINER' },
  { civilian: 'KUE CUBIT SETENGAH MATANG', undercover: 'KUE PUKIS KEJU COKELAT', category: '🧁 Jajanan Manis Empuk Harum', theme: 'KULINER' },
  { civilian: 'GELATO ITALIAN ICE CREAM', undercover: 'SORBET BUAH SEGAR ASAM', category: '🍨 Olahan Es Krim Premium', theme: 'KULINER' },
  { civilian: 'MACARON WARNA-WARNI', undercover: 'ECLAIR COKELAT PRANCIS', category: '🧁 Pastry Manis Lembut Khas Eropa', theme: 'KULINER' },
  { civilian: 'PUDING COKELAT SAUS FLA', undercover: 'JELLY AGAR-AGAR BUAH', category: '🍮 Makanan Penutup Kenyal Lembut', theme: 'KULINER' },

  // ════════════════════════════════════════════════════════════════════
  // 🎮 GAMING, ANIME, FILM & POP CULTURE (THEME: GAMING)
  // ════════════════════════════════════════════════════════════════════
  // Game Mobile & Esports
  { civilian: 'MOBILE LEGENDS: BANG BANG', undercover: 'FREE FIRE BATTLEGROUNDS', category: '🎮 Game Mobile Terpopuler', theme: 'GAMING' },
  { civilian: 'PUBG MOBILE', undercover: 'CALL OF DUTY: MOBILE', category: '🔫 Game Battle Royale HP', theme: 'GAMING' },
  { civilian: 'GENSHIN IMPACT', undercover: 'HONKAI: STAR RAIL', category: '✨ Game RPG Gacha HoYoverse', theme: 'GAMING' },
  { civilian: 'CLASH OF CLANS', undercover: 'CLASH ROYALE', category: '⚔️ Game Strategi Populer Supercell', theme: 'GAMING' },
  { civilian: 'ARENA OF VALOR (AOV)', undercover: 'HONOR OF KINGS (HOK)', category: '🛡️ Game MOBA Mobile 5v5', theme: 'GAMING' },
  { civilian: 'SUBWAY SURFERS', undercover: 'TEMPLE RUN 2', category: '🏃 Game Endless Runner Klasik HP', theme: 'GAMING' },
  { civilian: 'ANGRY BIRDS', undercover: 'PLANTS VS ZOMBIES', category: '🐦 Game Casual Nostalgia', theme: 'GAMING' },
  { civilian: 'CANDY CRUSH SAGA', undercover: 'HOMESCAPES', category: '🍬 Game Puzzle Santai Match-3', theme: 'GAMING' },
  { civilian: 'POKEMON GO AR', undercover: 'MONSTER HUNTER NOW', category: '📍 Game Eksplorasi Lokasi Nyata', theme: 'GAMING' },
  { civilian: 'EFOOTBALL MOBILE', undercover: 'EA SPORTS FC MOBILE', category: '⚽ Game Simulasi Sepakbola HP', theme: 'GAMING' },
  { civilian: 'ROBLOX VIRTUAL WORLD', undercover: 'MINECRAFT SURVIVAL', category: '🧱 Game Sandbox Dunia Kreatif', theme: 'GAMING' },
  { civilian: 'AMONG US SPACESHIP', undercover: 'GOOSE GOOSE DUCK', category: '🔪 Game Deduksi Sosial Impostor', theme: 'GAMING' },
  { civilian: 'STUMBLE GUYS PARTY', undercover: 'FALL GUYS ULTIMATE KNOCKOUT', category: '🤸 Game Party Rintangan Lucu', theme: 'GAMING' },
  { civilian: 'LEAGUE OF LEGENDS: WILD RIFT', undercover: 'DOTA 2 VALVE', category: '⚔️ Game MOBA Kompetitif', theme: 'GAMING' },
  { civilian: 'ASPHALT 9: LEGENDS', undercover: 'NEED FOR SPEED NO LIMITS', category: '🏎️ Game Balap Mobil Liar HP', theme: 'GAMING' },
  { civilian: 'HAY DAY PETERNAKAN', undercover: 'FARMVILLE PERKEBUNAN', category: '🌾 Game Simulasi Mengurus Kebun', theme: 'GAMING' },
  { civilian: 'SUMMONERS WAR', undercover: 'RAID: SHADOW LEGENDS', category: '🧙 Game Turn-Based RPG Gacha', theme: 'GAMING' },

  // Game PC & Konsol Terbesar
  { civilian: 'VALORANT RIOT GAMES', undercover: 'COUNTER-STRIKE 2 (CS2)', category: '🔫 Game Tactical FPS PC Esports', theme: 'GAMING' },
  { civilian: 'GTA V (GRAND THEFT AUTO)', undercover: 'CYBERPUNK 2077 NIGHT CITY', category: '🌆 Game Open World Megah', theme: 'GAMING' },
  { civilian: 'DOTA 2 THE INTERNATIONAL', undercover: 'LEAGUE OF LEGENDS WORLDS', category: '⚔️ Game MOBA PC Esports Terbesar', theme: 'GAMING' },
  { civilian: 'ELDEN RING LANDS BETWEEN', undercover: 'DARK SOULS III', category: '⚔️ Game Soulslike Penuh Tantangan', theme: 'GAMING' },
  { civilian: 'GOD OF WAR RAGNAROK', undercover: 'DEVIL MAY CRY 5', category: '🪓 Game Aksi Hack and Slash Dewa', theme: 'GAMING' },
  { civilian: 'RESIDENT EVIL VILLAGE', undercover: 'SILENT HILL 2', category: '🧟 Game Horor Survival Menegangkan', theme: 'GAMING' },
  { civilian: 'ASSASSIN\'S CREED VALHALLA', undercover: 'THE WITCHER 3 WILD HUNT', category: '🗡️ Game Petualangan Fantasi Epik', theme: 'GAMING' },
  { civilian: 'RED DEAD REDEMPTION 2', undercover: 'GTA SAN ANDREAS CJ', category: '🤠 Game Mahakarya Rockstar Games', theme: 'GAMING' },
  { civilian: 'SEKIRO: SHADOWS DIE TWICE', undercover: 'GHOST OF TSUSHIMA SAMURAI', category: '🗡️ Game Samurai Pertarungan Pedang', theme: 'GAMING' },
  { civilian: 'OVERWATCH 2 HEROES', undercover: 'APEX LEGENDS RESPAWN', category: '🎯 Game Hero Shooter Cepat', theme: 'GAMING' },
  { civilian: 'POINT BLANK GEMSCOOL', undercover: 'CROSSFIRE MEGAXUS', category: '🔫 Game FPS Warnet Zaman Dulu', theme: 'GAMING' },
  { civilian: 'LOST SAGA INDONESIA', undercover: 'DRAGON NEST ONLINE', category: '🥋 Game Warnet Nostalgia Indonesia', theme: 'GAMING' },
  { civilian: 'RAGNAROK ONLINE GRAVITY', undercover: 'SEAL ONLINE BLADE OF DESTINY', category: '🏰 Game MMORPG Klasik Asia', theme: 'GAMING' },
  { civilian: 'THE SIMS 4 KEHIDUPAN', undercover: 'ANIMAL CROSSING NEW HORIZONS', category: '🏡 Game Simulasi Kehidupan Santai', theme: 'GAMING' },
  { civilian: 'MONSTER HUNTER WORLD', undercover: 'HORIZON FORBIDDEN WEST', category: '🏹 Game Berburu Monster Raksasa', theme: 'GAMING' },
  { civilian: 'TEKKEN 8 MISHIMA', undercover: 'STREET FIGHTER 6 RYU', category: '🥊 Game Fighting Turnamen Esports', theme: 'GAMING' },
  { civilian: 'MORTAL KOMBAT 1 FATALITY', undercover: 'INJUSTICE GODS AMONG US', category: '🩸 Game Pertarungan Brutal Superhero', theme: 'GAMING' },
  { civilian: 'FORZA HORIZON 5 MEXICO', undercover: 'NEED FOR SPEED HEAT', category: '🏎️ Game Balap Mobil Open World', theme: 'GAMING' },
  { civilian: 'THE LAST OF US PART 1', undercover: 'UNCHARTED 4 NATHAN DRAKE', category: '🧗 Game Sinematik Naughty Dog', theme: 'GAMING' },
  { civilian: 'HOLLOW KNIGHT HALLOWNEST', undercover: 'ORI AND THE WILL OF THE WISPS', category: '🦋 Game Metroidvania Petualangan Indah', theme: 'GAMING' },
  { civilian: 'PALWORLD MONSTER WORK', undercover: 'POKEMON SCARLET VIOLET', category: '🐾 Game Menangkap Makhluk Fantasi', theme: 'GAMING' },
  { civilian: 'LETHAL COMPANY MOONS', undercover: 'PHASMOPHOBIA BERBURU HANTU', category: '👻 Game Co-op Horor Mencekam', theme: 'GAMING' },
  { civilian: 'LEFT 4 DEAD 2 ZOMBIE', undercover: 'BACK 4 BLOOD CLEANERS', category: '🧟 Game Tembak Zombie Co-op', theme: 'GAMING' },
  { civilian: 'BATTLEFIELD 2042', undercover: 'CALL OF DUTY WARZONE', category: '💥 Game Perang Militer Masif FPS', theme: 'GAMING' },

  // Konsol & Hardware Gaming
  { civilian: 'PLAYSTATION 5 (PS5)', undercover: 'XBOX SERIES X', category: '🎮 Konsol Game Generasi Terbaru', theme: 'GAMING' },
  { civilian: 'NINTENDO SWITCH OLED', undercover: 'STEAM DECK VALVE', category: '🕹️ Konsol Game Portabel Handheld', theme: 'GAMING' },
  { civilian: 'NINTENDO GAMEBOY COLOR', undercover: 'SONY PSP (PLAYSTATION PORTABLE)', category: '🕹️ Konsol Genggam Nostalgia', theme: 'GAMING' },
  { civilian: 'KEYBOARD MECHANICAL RGB', undercover: 'MOUSE GAMING HIGH DPI', category: '⌨️ Setup Aksesoris PC Gaming', theme: 'GAMING' },
  { civilian: 'HEADSET GAMING 7.1 SURROUND', undercover: 'EARPHONE TWS BLUETOOTH', category: '🎧 Aksesoris Audio Gaming', theme: 'GAMING' },
  { civilian: 'NVIDIA GEFORCE RTX', undercover: 'AMD RADEON RX', category: '🖥️ Kartu Grafis (GPU) Komputer', theme: 'GAMING' },
  { civilian: 'PROSESOR INTEL CORE I9', undercover: 'PROSESOR AMD RYZEN 9', category: '⚙️ Komponen Prosesor CPU Komputer', theme: 'GAMING' },

  // Anime & Manga Populer
  { civilian: 'NARUTO SHIPPUDEN', undercover: 'BORUTO NEXT GENERATIONS', category: '🍥 Serial Ninja Konoha', theme: 'GAMING' },
  { civilian: 'ONE PIECE MONKEY D LUFFY', undercover: 'BLEACH ICHIGO KUROSAKI', category: '🏴‍☠️ Anime Shonen Legendaris', theme: 'GAMING' },
  { civilian: 'ATTACK ON TITAN (SHINGEKI)', undercover: 'DEMON SLAYER (KIMETSU NO YAIBA)', category: '⚔️ Anime Aksi Melawan Monster', theme: 'GAMING' },
  { civilian: 'JUJUTSU KAISEN GOJO SATORU', undercover: 'CHAINSAW MAN DENJI', category: '👹 Anime Kutukan & Iblis Modern', theme: 'GAMING' },
  { civilian: 'DRAGON BALL Z GOKU', undercover: 'HUNTER X HUNTER GON FREECSS', category: '🐉 Anime Pertarungan Shonen Terkenal', theme: 'GAMING' },
  { civilian: 'DEATH NOTE LIGHT YAGAMI', undercover: 'CODE GEASS LELOUCH', category: '📓 Anime Taktik Otak & Manipulasi', theme: 'GAMING' },
  { civilian: 'SWORD ART ONLINE KIRITO', undercover: 'SOLO LEVELING SUNG JINWOO', category: '🗡️ Anime Dunia Game & Dungeon Hunter', theme: 'GAMING' },
  { civilian: 'MY HERO ACADEMIA DEKU', undercover: 'ONE PUNCH MAN SAITAMA', category: '🦸 Anime Pahlawan Super Kekuatan Unik', theme: 'GAMING' },
  { civilian: 'TOKYO GHOUL KANEKI KEN', undercover: 'PARASYTE MIGI', category: '🩸 Anime Monster Manusia Mutasi', theme: 'GAMING' },
  { civilian: 'SPY X FAMILY ANYA FORGER', undercover: 'KAGUYA-SAMA: LOVE IS WAR', category: '🥜 Anime Komedi & Romansa Populer', theme: 'GAMING' },
  { civilian: 'HAIKYUU!! HINATA SHOUYOU', undercover: 'BLUE LOCK ISAGI YOICHI', category: '⚽ Anime Olahraga Kompetitif Panas', theme: 'GAMING' },
  { civilian: 'SLAM DUNK HANAMICHI SAKURAGI', undercover: 'KUROKO NO BASKET SEIRIN', category: '🏀 Anime Olahraga Bola Basket', theme: 'GAMING' },
  { civilian: 'DORAEMON ROBOT KUCING', undercover: 'CRAYON SHINCHAN NOHARA', category: '🐱 Kartun Masa Kecil Minggu Pagi', theme: 'GAMING' },
  { civilian: 'DETECTIVE CONAN EDOGAWA', undercover: 'KAITO KID SI PENCURI SULAP', category: '🕵️ Karakter Misteri Pembunuhan Anime', theme: 'GAMING' },
  { civilian: 'FULLMETAL ALCHEMIST BROTHERHOOD', undercover: 'STEINS;GATE PERJALANAN WAKTU', category: '⚗️ Anime Mahakarya Sepanjang Masa', theme: 'GAMING' },
  { civilian: 'STUDIO GHIBLI SPIRITED AWAY', undercover: 'FILM MAKOTO SHINKAI KIMI NO NA WA', category: '🎬 Film Animasi Jepang Visual Indah', theme: 'GAMING' },
  { civilian: 'MANGA KOMIK JEPANG', undercover: 'MANHWA WEBTOON KOREA', category: '📚 Komik Bacaan Asia Bergambar', theme: 'GAMING' },
  { civilian: 'POKEMON PIKACHU', undercover: 'DIGIMON AGUMON', category: '⚡ Monster Hewan Berevolusi Digital', theme: 'GAMING' },
  { civilian: 'JOJO\'S BIZARRE ADVENTURE', undercover: 'FIST OF THE NORTH STAR', category: '💪 Anime Pria Berotot Pose Ikonik', theme: 'GAMING' },

  // Superhero, Film & TV Series
  { civilian: 'MARVEL CINEMATIC UNIVERSE (MCU)', undercover: 'DC EXTENDED UNIVERSE (DCEU)', category: '🦸 Semesta Superhero Terbesar', theme: 'GAMING' },
  { civilian: 'BATMAN BRUCE WAYNE', undercover: 'IRON MAN TONY STARK', category: '🦇 Miliarder Berbaju Zirah Pahlawan', theme: 'GAMING' },
  { civilian: 'SUPERMAN CLARK KENT', undercover: 'THOR DEWA PETIR ASGARD', category: '⚡ Superhero Berasal Dari Luar Angkasa', theme: 'GAMING' },
  { civilian: 'SPIDER-MAN PETER PARKER', undercover: 'DEADPOOL WADE WILSON', category: '🕷️ Pahlawan Kostum Merah Lincah & Humoris', theme: 'GAMING' },
  { civilian: 'JOKER MUSUH GOTHAM', undercover: 'THANOS PENGHANCUR SEMESTA', category: '🤡 Tokoh Penjahat Utama Paling Ikonik', theme: 'GAMING' },
  { civilian: 'HARRY POTTER HOGWARTS', undercover: 'LORD OF THE RINGS MIDDLE EARTH', category: '🧙 Film Fantasi Sihir & Kerajaan Epik', theme: 'GAMING' },
  { civilian: 'STAR WARS JEDI LIGHTSABER', undercover: 'STAR TREK PESAWAT ENTERPRISE', category: '🚀 Film Fiksi Luar Angkasa Epik', theme: 'GAMING' },
  { civilian: 'AVENGERS: ENDGAME', undercover: 'AVATAR: THE WAY OF WATER', category: '🎬 Film Terlaris Bioskop Dunia', theme: 'GAMING' },
  { civilian: 'STRANGER THINGS UPSIDE DOWN', undercover: 'WEDNESDAY ADDAMS', category: '📺 Serial Remaja Populer Netflix', theme: 'GAMING' },
  { civilian: 'SQUID GAME KOREA', undercover: 'ALICE IN BORDERLAND JEPANG', category: '🦑 Serial Bertahan Hidup Permainan Maut', theme: 'GAMING' },
  { civilian: 'MONEY HEIST (LA CASA DE PAPEL)', undercover: 'BREAKING BAD WALTER WHITE', category: '🎭 Serial Drama Kejahatan Kriminal Jenius', theme: 'GAMING' },
  { civilian: 'PEAKY BLINDERS THOMAS SHELBY', undercover: 'THE GODFATHER MAFIA', category: '🥃 Kisah Gangster Mafia Berkelas', theme: 'GAMING' },
  { civilian: 'GAME OF THRONES WESTEROS', undercover: 'HOUSE OF THE DRAGON TARGARYEN', category: '🐉 Serial Perebutan Tahta & Naga Api', theme: 'GAMING' },
  { civilian: 'INTERSTELLAR LUBANG HITAM', undercover: 'INCEPTION DUNIA MIMPI', category: '🌌 Film Fiksi Ilmiah Sutradara Nolan', theme: 'GAMING' },
  { civilian: 'FAST & FURIOUS DOM TORETTO', undercover: 'TRANSFORMERS OPTIMUS PRIME', category: '🏎️ Film Aksi Balap Mobil & Aksi Masif', theme: 'GAMING' },
  { civilian: 'JURASSIC PARK DINOSAURUS', undercover: 'KING KONG PULAU TENGKORAK', category: '🦖 Film Monster Purba Raksasa Liar', theme: 'GAMING' },
  { civilian: 'GODZILLA RAJA MONSTER', undercover: 'PACIFIC RIM ROBOT JAEGER', category: '💥 Film Pertarungan Kaiju Monster Raksasa', theme: 'GAMING' },
  { civilian: 'TITANIC JACK DAN ROSE', undercover: 'LA LA LAND MUSIKAL', category: '🚢 Film Drama Romansa Kisah Cinta Mengharukan', theme: 'GAMING' },
  { civilian: 'THE CONJURING VALAK', undercover: 'INSIDIOUS DUNIA ARWAH', category: '👻 Semesta Film Horor Kerasukan Iblis', theme: 'GAMING' },
  { civilian: 'PENGABDI SETAN IBU', undercover: 'KKN DI DESA PENARI BADARAWUHI', category: '🧟 Film Horor Terlaris Indonesia', theme: 'GAMING' },
  { civilian: 'LASKAR PELANGI BELITUNG', undercover: 'ADA APA DENGAN CINTA (AADC)', category: '🎬 Film Drama Klasik Indonesia', theme: 'GAMING' },

  // Musik, Band & Platform
  { civilian: 'SPOTIFY PREMIUM', undercover: 'APPLE MUSIC LOSSLESS', category: '🎵 Platform Streaming Musik Digital', theme: 'GAMING' },
  { civilian: 'NETFLIX STREAMING', undercover: 'DISNEY+ HOTSTAR', category: '🎬 Layanan Streaming Film Berlangganan', theme: 'GAMING' },
  { civilian: 'YOUTUBE KONTEN', undercover: 'TIKTOK FOR YOU PAGE (FYP)', category: '📹 Platform Konten Video Kreator', theme: 'GAMING' },
  { civilian: 'TWITCH LIVE STREAM', undercover: 'YOUTUBE GAMING STREAM', category: '🎙️ Platform Siaran Langsung Gamers', theme: 'GAMING' },
  { civilian: 'BTS KOREA (BANGTAN)', undercover: 'BLACKPINK K-POP', category: '🎤 Grup Musik K-Pop Terbesar Dunia', theme: 'GAMING' },
  { civilian: 'COLDPLAY CHRIS MARTIN', undercover: 'MAROON 5 ADAM LEVINE', category: '🎸 Grup Band Pop Rock Panggung Dunia', theme: 'GAMING' },
  { civilian: 'SHEILA ON 7 DUTA', undercover: 'DEWA 19 AHMAD DHANI', category: '🎸 Band Musik Legendaris Indonesia', theme: 'GAMING' },
  { civilian: 'TULUS MUSISI', undercover: 'HINDIA BASKARA', category: '🎙️ Solois Musik Populer Tanah Air', theme: 'GAMING' },
  { civilian: 'TAYLOR SWIFT ERAS TOUR', undercover: 'BILLIE EILISH POP', category: '👑 Penyanyi Pop Wanita Terbesar Dunia', theme: 'GAMING' },
  { civilian: 'EMINEM RAP GOD', undercover: 'DRAKE HIP HOP', category: '🎤 Rapper Bintang Hip Hop Kelas Dunia', theme: 'GAMING' },

  // ════════════════════════════════════════════════════════════════════
  // 🏠 KEHIDUPAN, SOSIAL, ASMARA & BUDAYA MODERN (THEME: SOSIAL)
  // ════════════════════════════════════════════════════════════════════
  // Kehidupan Kampus, Kosan & Sekolah
  { civilian: 'KAMAR KOSAN', undercover: 'RUMAH KONTRAKAN', category: '🏠 Tempat Sewa Hunian Mahasiswa', theme: 'SOSIAL' },
  { civilian: 'SKRIPSI BAB 1-5', undercover: 'TUGAS AKHIR KELULUSAN', category: '🎓 Ujian Akhir Gelar Sarjana Kuliah', theme: 'SOSIAL' },
  { civilian: 'DOSEN PEMBIMBING (DOSBIM)', undercover: 'DOSEN PENGUJI SIDANG', category: '👔 Sosok Penentu Kelulusan Kuliah', theme: 'SOSIAL' },
  { civilian: 'IPK CUMLAUDE (3.8+)', undercover: 'IPK PAS-PASAN (2.5)', category: '📜 Nilai Rapor Prestasi Akademik Kuliah', theme: 'SOSIAL' },
  { civilian: 'OSPEK MAHASISWA BARU', undercover: 'MOS MASA ORIENTASI SEKOLAH', category: '🧢 Masa Pengenalan Siswa Baru', theme: 'SOSIAL' },
  { civilian: 'TITIP ABSEN (TA KELAS)', undercover: 'BOLOS KELAS KULIAH', category: '🏃 Kenakalan Mahasiswa di Kampus', theme: 'SOSIAL' },
  { civilian: 'KANTIN KAMPUS MAHASISWA', undercover: 'WARKOP DEPAN KAMPUS', category: '☕ Tempat Nongkrong Mahasiswa Santai', theme: 'SOSIAL' },
  { civilian: 'BEASISWA KIP-KULIAH', undercover: 'BEASISWA LPDP KEMENKEU', category: '💵 Bantuan Dana Beasiswa Pendidikan', theme: 'SOSIAL' },
  { civilian: 'MAGANG KANTOR (INTERNSHIP)', undercover: 'KERJA PRAKTIK (KP LAPANGAN)', category: '🏢 Pengalaman Kerja Pra-Lulus Mahasiswa', theme: 'SOSIAL' },
  { civilian: 'WISUDA TOGA SARJANA', undercover: 'YUDISIUM KELULUSAN', category: '🎓 Upacara Perayaan Kelulusan Kampus', theme: 'SOSIAL' },
  { civilian: 'KERJA KELOMPOK DI KAFE', undercover: 'BELAJAR BARENG DI PERPUSTAKAAN', category: '📚 Aktivitas Mengerjakan Tugas Kampus', theme: 'SOSIAL' },
  { civilian: 'KARTU TANDA MAHASISWA (KTM)', undercover: 'KARTU PELAJAR SEKOLAH', category: '💳 Kartu Identitas Pendidikan', theme: 'SOSIAL' },
  { civilian: 'PR PEKERJAAN RUMAH', undercover: 'ULANGAN HARIAN UJIAN', category: '📝 Beban Belajar Murid di Sekolah', theme: 'SOSIAL' },
  { civilian: 'SERAGAM PUTIH ABU-ABU SMA', undercover: 'JAS ALMAMATER KAMPUS', category: '👔 Pakaian Identitas Pelajar & Mahasiswa', theme: 'SOSIAL' },
  { civilian: 'IBU KOS GALAK', undercover: 'BAPAK KOS SANTAI', category: '🏠 Pemilik Kos-Kosan Mahasiswa', theme: 'SOSIAL' },

  // Asmara, Percintaan & Hubungan
  { civilian: 'MANTAN PACAR', undercover: 'GEBETAN BARU', category: '💔 Sosok Pengisi Hati Manusia', theme: 'SOSIAL' },
  { civilian: 'PACARAN RESMI', undercover: 'HTS (HUBUNGAN TANPA STATUS)', category: '💘 Status Ikatan Hubungan Percintaan', theme: 'SOSIAL' },
  { civilian: 'APLIKASI DATING (TINDER/BUMBLE)', undercover: 'KENALAN LEWAT DM INSTAGRAM', category: '📱 Cara Mencari Jodoh Online', theme: 'SOSIAL' },
  { civilian: 'FRIENDZONE (CUMA TEMAN)', undercover: 'BROTHERZONE (DIANGGAP ABANG)', category: '🥺 Terjebak Status Hubungan Menggantung', theme: 'SOSIAL' },
  { civilian: 'KONDANGAN PERNIKAHAN MANTAN', undercover: 'REUNI TEMAN SEKOLAH', category: '👗 Acara Formal Kumpul Kerabat', theme: 'SOSIAL' },
  { civilian: 'GHOSTING MENGHILANG TIBA-TIBA', undercover: 'SLOW RESPOND BALAS CHAT', category: '👻 Sikap Menghindar Dalam Chatting', theme: 'SOSIAL' },
  { civilian: 'FIRST DATE KENCAN PERTAMA', undercover: 'ANNIVERSARY PERAYAAN TAHUNAN', category: '🌹 Momen Kencan Spesial Pasangan', theme: 'SOSIAL' },
  { civilian: 'LAMARAN TUKAR CINCIN', undercover: 'AKAD NIKAH IJAB KABUL', category: '💍 Prosesi Sakral Jenjang Rumah Tangga', theme: 'SOSIAL' },
  { civilian: 'BUCIN (BUDAK CINTA RELA BERKORBAN)', undercover: 'GENGSI TINGGI ENGGAN CHAT DULUAN', category: '🥺 Sikap Karakter Dalam Percintaan', theme: 'SOSIAL' },
  { civilian: 'SELINGKUH DI BELAKANG', undercover: 'CINTA BERTEPUK SEBELAH TANGAN', category: '💔 Patah Hati & Kekecewaan Hubungan', theme: 'SOSIAL' },
  { civilian: 'OVERTHINKING MIKIRIN MASA DEPAN', undercover: 'BEGADANG NONTON FILM SAMPAI SUBUH', category: '🌙 Kebiasaan Larut Malam Kaum Muda', theme: 'SOSIAL' },
  { civilian: 'CURHAT DI TWITTER / X', undercover: 'BAPER LIHAT KONTEN TIKTOK GALAU', category: '📱 Melampiaskan Perasaan di Media Sosial', theme: 'SOSIAL' },
  { civilian: 'CINTA MONYET ZAMAN SMP', undercover: 'CINTA PERTAMA (FIRST LOVE)', category: '🥰 Kenangan Asmara Masa Remaja', theme: 'SOSIAL' },
  { civilian: 'NGEDATE NONTON DI BIOSKOP', undercover: 'NGEDATE NGOPI DI KAFE AESTHETIC', category: '🍿 Pilihan Aktivitas Kencan Romantis', theme: 'SOSIAL' },
  { civilian: 'KADO ULANG TAHUN COKELAT', undercover: 'BUKET BUNGA MAWAR MERAH', category: '🎁 Hadiah Romantis Untuk Pasangan', theme: 'SOSIAL' },

  // Pekerjaan, Kantor & Finansial
  { civilian: 'GAJI UMR DAERAH', undercover: 'PENGHASILAN FREELANCE DIGITAL', category: '💵 Sumber Pendapatan Bulanan Pekerja', theme: 'SOSIAL' },
  { civilian: 'THR TUNJANGAN HARI RAYA', undercover: 'BONUS TAHUNAN KINERJA KANTOR', category: '🎁 Rezeki Finansial Tambahan Karyawan', theme: 'SOSIAL' },
  { civilian: 'PINJOL (PINJAMAN ONLINE ILEGAL)', undercover: 'PAYLATER APLIKASI BELANJA', category: '💳 Fasilitas Hutang Digital Cepat Cair', theme: 'SOSIAL' },
  { civilian: 'INVESTASI SAHAM BLUE CHIP', undercover: 'TRADING CRYPTO BITCOIN', category: '📈 Penanaman Modal Finansial Digital', theme: 'SOSIAL' },
  { civilian: 'HRD KANTOR REKRUTMEN', undercover: 'USER INTERVIEW MANAGER', category: '👔 Sosok Penguji Seleksi Lamaran Kerja', theme: 'SOSIAL' },
  { civilian: 'WORK FROM HOME (WFH DARI RUMAH)', undercover: 'WORK FROM OFFICE (WFO DI KANTOR)', category: '💻 Sistem Tempat Bekerja Karyawan', theme: 'SOSIAL' },
  { civilian: 'SURAT PERINGATAN (SP KANTOR)', undercover: 'SURAT PEMUTUSAN HUBUNGAN KERJA (PHK)', category: '📄 Sanksi Kedisiplinan Karyawan Kantor', theme: 'SOSIAL' },
  { civilian: 'LEMBUR KERJA SAMPAI MALAM', undercover: 'BURNOUT KELAPARAN ENERGI KANTOR', category: '😫 Beban Kelelahan Dunia Kerja', theme: 'SOSIAL' },
  { civilian: 'REKENING TABUNGAN BANK BCA', undercover: 'DOMPET DIGITAL E-WALLET GOPAY DANA', category: '💳 Tempat Penyimpanan Saldo Uang', theme: 'SOSIAL' },
  { civilian: 'DANA DARURAT DEPOSITO', undercover: 'ASURANSI KESEHATAN BPJS KESEHATAN', category: '🏥 Proteksi Finansial Perlindungan Diri', theme: 'SOSIAL' },
  { civilian: 'SELEKSI CPNS PEMERINTAH', undercover: 'REKRUTMEN BERSAMA BUMN NEGARA', category: '🏛️ Ujian Masuk Pegawai Idaman Mertua', theme: 'SOSIAL' },
  { civilian: 'KARYAWAN TETAP KANTOR', undercover: 'PEGAWAI KONTRAK OUTSOURCING', category: '📝 Status Ikatan Perjanjian Kerja', theme: 'SOSIAL' },
  { civilian: 'KARTU KREDIT LIMIT BESAR', undercover: 'KARTU DEBIT ATM SALDO MINIMALIS', category: '💳 Kartu Transaksi Plastik Perbankan', theme: 'SOSIAL' },
  { civilian: 'TRANSFER BANK BI-FAST (RP 2.500)', undercover: 'QRIS SCAN PEMBAYARAN INSTAN', category: '📲 Metode Transaksi Keuangan Harian', theme: 'SOSIAL' },
  { civilian: 'JATAH CUTI TAHUNAN KANTOR', undercover: 'SURAT SAKIT DOKTER KLINIK', category: '🏖️ Alasan Izin Tidak Masuk Kerja', theme: 'SOSIAL' },

  // Aplikasi, Medsos & Dunia Digital
  { civilian: 'WHATSAPP CHAT GRUP', undercover: 'TELEGRAM CHANNEL BOT', category: '💬 Aplikasi Pesan Singkat Populer', theme: 'SOSIAL' },
  { civilian: 'INSTAGRAM STORY & REELS', undercover: 'TIKTOK VIDEO FYP VIRAL', category: '📱 Media Sosial Konten Video & Foto', theme: 'SOSIAL' },
  { civilian: 'TWITTER (X CITIZEN JURNALIS)', undercover: 'THREADS INSTAGRAM APLIKASI', category: '🐦 Platform Media Sosial Berbasis Teks', theme: 'SOSIAL' },
  { civilian: 'SHOPEE DISKON GRATIS ONGKIR', undercover: 'TOKOPEDIA CASHBACK OFFICIAL STORE', category: '🛍️ Marketplace Belanja Online Terbesar', theme: 'SOSIAL' },
  { civilian: 'GOJEK GORIDE GOMART', undercover: 'GRABBIKE GRABFOOD DISKON', category: '🛵 Super App Ojek & Pesan Makanan', theme: 'SOSIAL' },
  { civilian: 'GOOGLE DRIVE 15GB', undercover: 'APPLE ICLOUD STORAGE', category: '☁️ Layanan Cloud Penyimpanan File', theme: 'SOSIAL' },
  { civilian: 'GOOGLE MAPS GPS PETUNJUK', undercover: 'WAZE NAVIGASI MACET POLISI', category: '🗺️ Aplikasi Peta Penunjuk Arah Jalan', theme: 'SOSIAL' },
  { civilian: 'ZOOM MEETING VIRTUAL BACKGROUND', undercover: 'GOOGLE MEET VIDEO CALL', category: '📹 Aplikasi Rapat Daring Jarak Jauh', theme: 'SOSIAL' },
  { civilian: 'CANVA TEMPLATE PRAKTIS', undercover: 'ADOBE PHOTOSHOP DESAIN PRO', category: '🎨 Software Alat Desain Grafis Visual', theme: 'SOSIAL' },
  { civilian: 'CHATGPT OPENAI AI ASISTEN', undercover: 'GOOGLE GEMINI PRO ARTIFICIAL INTEL', category: '🤖 Kecerdasan Buatan (AI) Generatif', theme: 'SOSIAL' },
  { civilian: 'CAPCUT TEMPLATE TIKTOK', undercover: 'ADOBE PREMIERE PRO TIMELINE', category: '🎬 Software Alat Editing Video Konten', theme: 'SOSIAL' },
  { civilian: 'LINKEDIN NETWORKING KARIER', undercover: 'JOBSTREET LAMARAN KERJA', category: '👔 Platform Pencarian Lowongan Kerja', theme: 'SOSIAL' },
  { civilian: 'WIFI INDIHOME / TELKOMSEL', undercover: 'PAKET DATA INTERNET KUOTA HABIS', category: '📶 Jaringan Koneksi Internet Rumah & HP', theme: 'SOSIAL' },

  // Jalanan, Transportasi & Kehidupan Kota
  { civilian: 'OJEK ONLINE (DRIVER OJOL)', undercover: 'TAKSI BLUE BIRD ARGO', category: '🛵 Transportasi Umum Panggilan Jalan', theme: 'SOSIAL' },
  { civilian: 'KRL COMMUTER LINE JABODETABEK', undercover: 'MRT JAKARTA BAWAH TANAH', category: '🚆 Transportasi Kereta Rel Perkotaan', theme: 'SOSIAL' },
  { civilian: 'BUS TRANSJAKARTA KORIDOR', undercover: 'ANGKUTAN KOTA (ANGKOT KELILING)', category: '🚌 Transportasi Bus Jalan Raya Aspal', theme: 'SOSIAL' },
  { civilian: 'KARCIS PARKIR MOTOR HILANG', undercover: 'HELM HILANG DICURI DI PARKIRAN', category: '🛵 Drama Parkiran Kendaraan Bermotor', theme: 'SOSIAL' },
  { civilian: 'SATPOL PP PENERTIBAN', undercover: 'PEDAGANG KAKI LIMA (PKL GEROBAK)', category: '👮 Penertiban Trotoar Jalanan Kota', theme: 'SOSIAL' },
  { civilian: 'SURAT TILANG RAZIA POLISI', undercover: 'KAMERA ETLE TILANG ELEKTRONIK', category: '👮 Penindakan Pelanggaran Lalu Lintas', theme: 'SOSIAL' },
  { civilian: 'STNK SURAT TANDA NOMOR KENDARAAN', undercover: 'BPKB BUKU PEMILIK KENDARAAN', category: '📄 Surat Bukti Legalitas Motor / Mobil', theme: 'SOSIAL' },
  { civilian: 'SIM C SURAT IZIN MOTOR', undercover: 'SIM A SURAT IZIN MOBIL', category: '🪪 Lisensi Pengemudi Resmi Kepolisian', theme: 'SOSIAL' },
  { civilian: 'LAMPU MERAH PERSIMPANGAN JALAN', undercover: 'POLISI TIDUR TINGGI ASPAL', category: '🚦 Sarana Pengatur Kecepatan Kendaraan', theme: 'SOSIAL' },
  { civilian: 'MACET TOTAL JAM PULANG KANTOR', undercover: 'BANJIR GENANGAN AIR HUJAN DERAS', category: '🚗 Pemicu Keterlambatan Perjalanan Kota', theme: 'SOSIAL' },
  { civilian: 'JALAN TOL BEBAS HAMBATAN', undercover: 'JALAN TIKUS GANG SEMPIT PERKAMPUNGAN', category: '🛣️ Pilihan Rute Perjalanan Pengendara', theme: 'SOSIAL' },
  { civilian: 'SPBU PERTAMINA MERAH PASTI PAS', undercover: 'SPBU SHELL V-POWER NITRO', category: '⛽ Tempat Pengisian Bahan Bakar Bensin', theme: 'SOSIAL' },
  { civilian: 'TAMBAL BAN MOTOR TUBELLES', undercover: 'CUCI STEAM MOTOR KINCLONG', category: '🛵 Jasa Perawatan Kendaraan di Jalan', theme: 'SOSIAL' },
  { civilian: 'JAS HUJAN PONCO / SETELAN', undercover: 'PAYUNG LIPAT KANTONG', category: '🌧️ Perlengkapan Penangkal Air Hujan', theme: 'SOSIAL' },
  { civilian: 'MINIMARKET INDOMARET 24 JAM', undercover: 'MINIMARKET ALFAMART TETANGGA', category: '🏪 Jaringan Retail Minimarket Waralaba', theme: 'SOSIAL' },
  { civilian: 'WARKOP INDOMIE TELUR KORNET', undercover: 'KAFE AESTHETIC MINIMALIS', category: '☕ Tempat Nongkrong Santai Anak Muda', theme: 'SOSIAL' },
  { civilian: 'MUDIK PULANG KAMPUNG HALAMAN', undercover: 'LIBURAN STAYCATION KE HOTEL', category: '🧳 Agenda Perjalanan Liburan Tahunan', theme: 'SOSIAL' },
  { civilian: 'PASAR MALAM DANGDUT & KORIDOR', undercover: 'FESTIVAL BAZAR KULINER KEKINIAN', category: '🎡 Hiburan Keramaian Rakyat & Jajanan', theme: 'SOSIAL' },

  // ════════════════════════════════════════════════════════════════════
  // 🐾 HEWAN, PROFESI, GADGET, FASHION & TEMPAT (THEME: ALAM)
  // ════════════════════════════════════════════════════════════════════
  // Hewan & Satwa Liar
  { civilian: 'KUCING PERSIA BULU LEBAT', undercover: 'KUCING ORANGE KAMPUNG BAR-BAR', category: '🐱 Satwa Peliharaan Rumahan Favorit', theme: 'ALAM' },
  { civilian: 'HARIMAU SUMATERA BELANG', undercover: 'SINGA AFRIKA RAJA HUTAN', category: '🦁 Kucing Besar Predator Karnivora Puncak', theme: 'ALAM' },
  { civilian: 'SERIGALA HUTAN ARTIK', undercover: 'ANJING HERDER GEMBALA JERMAN', category: '🐺 Hewan Keluarga Taring Berkaki Empat', theme: 'ALAM' },
  { civilian: 'GAJAH BELALAI PANJANG', undercover: 'BADAK BERCAULA SATU UJUNG KULON', category: '🦏 Mamalia Darat Berbadan Raksasa Kulit Tebal', theme: 'ALAM' },
  { civilian: 'JERAPAH LEHER PANJANG', undercover: 'ZEBRA BERGARIS HITAM PUTIH', category: '🦒 Hewan Herbivora Padang Savana Afrika', theme: 'ALAM' },
  { civilian: 'BUAYA RAWA MUARA SUNGAI', undercover: 'ALLIGATOR AMERIKA', category: '🐊 Reptil Predator Air Tawar Bergigi Tajam', theme: 'ALAM' },
  { civilian: 'ULAR KOBRA SENDOK BERBISA', undercover: 'ULAR PITON RETICULATUS RAKSASA', category: '🐍 Reptil Melata Predator Mematikan', theme: 'ALAM' },
  { civilian: 'IKAN HIU MEGALODON GIGI TAJAM', undercover: 'IKAN PAUS BIRU TERBESAR DI BUMI', category: '🦈 Penguasa Samudra Lautan Dalam', theme: 'ALAM' },
  { civilian: 'LUMBA-LUMBA CERDAS AKROBATIK', undercover: 'ANJING LAUT / SINGA LAUT KUTUB', category: '🐬 Mamalia Laut Cerdas & Lucu Bersuara', theme: 'ALAM' },
  { civilian: 'BURUNG ELANG JAWA PENGLIHATAN', undercover: 'BURUNG HANTU MALAM HARI', category: '🦉 Burung Pemangsa Karnivora Udara', theme: 'ALAM' },
  { civilian: 'AYAM JAGO KOKOK PAGI', undercover: 'BEBEK ANGSA PUTIH LEHER PANJANG', category: '🦆 Unggas Peliharaan Peternakan Desa', theme: 'ALAM' },
  { civilian: 'KAMBING QURBAN BANDOT', undercover: 'SAPI PERAH PENGHASIL SUSU', category: '🐄 Hewan Ternak Pemakan Rumput Hijau', theme: 'ALAM' },
  { civilian: 'KUDA PACU LAPANGAN STAMINA', undercover: 'UNTA PADANG PASIR TAHAN HAUS', category: '🐎 Hewan Tunggangan Berstamina Kuat', theme: 'ALAM' },
  { civilian: 'MONYET EKOR PANJANG NAKAL', undercover: 'ORANGUTAN KALIMANTAN PRIMATA', category: '🦧 Primata Hutan Tropis Cerdas Berbulu', theme: 'ALAM' },
  { civilian: 'KANGURU LOMPAT AUSTRALIA', undercover: 'KOALA PENGANTUK POHON EUKALIPTUS', category: '🐨 Hewan Berkantung Mamalia Australia', theme: 'ALAM' },
  { civilian: 'PENGUIN KUTUB SELATAN ANTARgame', undercover: 'BERUANG KUTUB PUTIH CARNIVORA', category: '🐧 Satwa Penghuni Benua Es Dingin Beku', theme: 'ALAM' },
  { civilian: 'BUNGLON PENYAMAR WARNA KULIT', undercover: 'KOMODO NAGA PURBA PULAU KOMODO', category: '🦎 Reptil Eksotis Predator Endemik', theme: 'ALAM' },
  { civilian: 'NYAMUK DEMAM BERDARAH DBD', undercover: 'LALAT HIJAU SAMPAH KOTOR', category: '🦟 Serangga Pengganggu Kesehatan Rumah', theme: 'ALAM' },
  { civilian: 'LEBAH MADU PENGHASIL SENGAT', undercover: 'SEMUT RANGKANG MERAH GIGIT', category: '🐝 Serangga Pekerja Berkoloni Ratu', theme: 'ALAM' },
  { civilian: 'KUPU-KUPU METAMORFOSIS CANTIK', undercover: 'CAPUNG JARUM TERBANG AIR', category: '🦋 Serangga Bersayap Indah Taman Bunga', theme: 'ALAM' },
  { civilian: 'LABA-LABA SARANG JARING RAJUT', undercover: 'KALAJENGKING EKOR RACUN BISA', category: '🕷️ Hewan Berbisa Berkaki Delapan Berbahaya', theme: 'ALAM' },
  { civilian: 'IKAN CUPANG ADUAN WARNA-WARNI', undercover: 'IKAN MAS KOKI PERUT BUNCIT', category: '🐠 Ikan Hias Air Tawar Cantik Akuarium', theme: 'ALAM' },
  { civilian: 'PENYU LAUT BERTELUR PANTAI', undercover: 'KURA-KURA DARAT BATOK TEMPURUNG', category: '🐢 Reptil Bertempurung Keras Berumur Panjang', theme: 'ALAM' },
  { civilian: 'KELELAWAR KALONG PENGHISAP BUAH', undercover: 'BURUNG WALET AIR LIUR MAHAL', category: '🦇 Penghuni Gua Gelap Malam Hari Berkelompok', theme: 'ALAM' },

  // Profesi & Pekerjaan
  { civilian: 'DOKTER SPESIALIS BEDAH', undercover: 'PERAWAT MEDIS RUMAH SAKIT', category: '🏥 Tenaga Kesehatan Penyelamat Nyawa', theme: 'ALAM' },
  { civilian: 'POLISI LALU LINTAS KORLANTAS', undercover: 'SATPAM KEAMANAN GEDUNG POS', category: '👮 Petugas Penjaga Ketertiban & Keamanan', theme: 'ALAM' },
  { civilian: 'TENTARA NASIONAL INDONESIA (TNI)', undercover: 'ANGGOTA PRAMUKA PRAJA MUDA KARANA', category: '🪖 Pasukan Berseragam Cokelat/Loreng Disiplin', theme: 'ALAM' },
  { civilian: 'PILOT PESAWAT TERBANG KOMERSIAL', undercover: 'MASINIS KERETA API KAI', category: '👨‍✈️ Pengemudi Transportasi Angkutan Publik', theme: 'ALAM' },
  { civilian: 'NAKHODA KAPAL LAUT SAMUDRA', undercover: 'SUPIR BUS MALAM CEPAT AKAP', category: '🚢 Pengemudi Rute Jarak Jauh Penumpang', theme: 'ALAM' },
  { civilian: 'GURU PENGAJAR SEKOLAH DASAR', undercover: 'DOSEN GURU BESAR UNIVERSITAS', category: '👨‍🏫 Pendidik Generasi Penerus Bangsa', theme: 'ALAM' },
  { civilian: 'HAKIM KETUA MAHKAMAH PERSIDANGAN', undercover: 'PENGACARA HUKUM / ADVOKAT', category: '⚖️ Penegak Hukum di Meja Hijau Pengadilan', theme: 'ALAM' },
  { civilian: 'PETUGAS PEMADAM KEBAKARAN (DAMKAR)', undercover: 'TIM SAR PENYELAMAT BASARNAS', category: '🚒 Pasukan Penyelamat Evakuasi Bencana Kritis', theme: 'ALAM' },
  { civilian: 'ARSITEK GAMBAR RANCANG GEDUNG', undercover: 'KONTRAKTOR PROYEK MANDOR TUKANG', category: '🏗️ Perancang & Pelaksana Konstruksi Bangunan', theme: 'ALAM' },
  { civilian: 'CHEF KOKI KEPALA RESTORAN BINTANG', undercover: 'BARISTA RACIK BIJI KOPI KAFE', category: '👨‍🍳 Peracik Hidangan Santapan & Minuman Citarasa', theme: 'ALAM' },
  { civilian: 'SOFTWARE ENGINEER PROGRAMMER KODING', undercover: 'TEKNISI IT SERVICE KOMPUTER', category: '💻 Profesi Bidang Teknologi Digital Perangkat', theme: 'ALAM' },
  { civilian: 'AKUNTAN AUDITOR KEUANGAN LAPORAN', undercover: 'KASIR MESIN PEMBAYARAN TOKO', category: '💰 Pengelola Perhitungan Angka & Uang Kas', theme: 'ALAM' },
  { civilian: 'WARTAWAN JURNALIS LIPUTAN BERITA', undercover: 'FOTOGRAFER KAMERA LENSA TELE', category: '📸 Pemburu Berita Fakta & Visual Momen', theme: 'ALAM' },
  { civilian: 'ASTRONOT PENJELAJAH LUAR ANGKASA', undercover: 'ILMUWAN PENELITI LABORATORIUM SAINS', category: '🚀 Peneliti Sains Pengetahuan Alam Semesta', theme: 'ALAM' },
  { civilian: 'TUKANG CUKUR RAMBUT BARBERSHOP', undercover: 'MAKEUP ARTIST (MUA) PENATA RIAS', category: '💇 Jasa Kerapian Penampilan & Estetika Wajah', theme: 'ALAM' },
  { civilian: 'NELAYAN KAPAL PENJARING IKAN LAUT', undercover: 'PETANI PADI SAWAH PEMANEN GABAH', category: '🌾 Pahlawan Penghasil Pangan Pokok Masyarakat', theme: 'ALAM' },
  { civilian: 'KURIR PAKET EKSPEDISI J&T JNE', undercover: 'TUKANG POS PENGANTAR SURAT RESMI', category: '📦 Petugas Pengantar Barang Kiriman Rumah', theme: 'ALAM' },

  // Benda, Elektronik & Perangkat
  { civilian: 'SMARTPHONE IPHONE APPLE iOS', undercover: 'HP SMARTPHONE SAMSUNG ANDROID', category: '📱 Perangkat Gadget Komunikasi Genggam Harian', theme: 'ALAM' },
  { civilian: 'LAPTOP TIPIS ULTRABOOK KERJA', undercover: 'KOMPUTER DESKTOP PC TOWER MONITOR', category: '💻 Perangkat Komputasi Pengolah Data Kerja', theme: 'ALAM' },
  { civilian: 'SMART TV 4K ANDROID TELEVISI', undercover: 'PROYEKTOR LAYAR BIOSKOP PROJECTION', category: '📺 Layar Tontonan Visual Audio Hiburan', theme: 'ALAM' },
  { civilian: 'KAMERA DSLR SENSOR BESAR CANON', undercover: 'KAMERA MIRRORLESS RINGKAS SONY', category: '📷 Alat Fotografi Jepretan Momen Gambar', theme: 'ALAM' },
  { civilian: 'POWERBANK FAST CHARGING KANTUNG', undercover: 'KABEL DATA CHARGER TYPE-C COLOKAN', category: '🔋 Pengisi Daya Arus Baterai Smartphone', theme: 'ALAM' },
  { civilian: 'FLASHDISK USB PORTABEL KECIL', undercover: 'HARDDISK EKSTERNAL 1TB BESAR', category: '💾 Perangkat Simpan Penyimpanan File Cadangan', theme: 'ALAM' },
  { civilian: 'SMARTWATCH DETEKSI DETAK JANTUNG', undercover: 'JAM TANGAN ANALOG JARUM MEKANIK', category: '⌚ Aksesoris Penunjuk Waktu di Pergelangan Tangan', theme: 'ALAM' },
  { civilian: 'KULKAS DUA PINTU INVERTER DINGIN', undercover: 'FREEZER BOX PEMBEKU DAGING IKAN', category: '🧊 Perangkat Mesin Pendingin Makanan Dapur', theme: 'ALAM' },
  { civilian: 'MESIN CUCI OTOMATIS SATU TABUNG', undercover: 'SETRIKA UAP PAKAIAN PANAS RAPI', category: '👕 Perlengkapan Kebersihan Busana Pakaian', theme: 'ALAM' },
  { civilian: 'AIR CONDITIONER (AC) DINGIN 1 PK', undercover: 'KIPAS ANGIN BALING-BALING ANGIN', category: '❄️ Penyejuk Sirkulasi Udara Suhu Ruangan', theme: 'ALAM' },
  { civilian: 'MICROWAVE PEMANAS CEPAT MAKANAN', undercover: 'OVEN PANGGANG ROTI LISTRIK SUHU', category: '🍞 Alat Pemanas Makanan Dapur Elektronik', theme: 'ALAM' },
  { civilian: 'RICE COOKER MAGIC COM PENANAK NASI', undercover: 'KOMPOR GAS DUA TUNGKU API BIRU', category: '🍚 Perlengkapan Utama Memasak Makanan Dapur', theme: 'ALAM' },
  { civilian: 'VACUUM CLEANER PENYEDOT DEBU KARPET', undercover: 'SAPU IJUK TRADISIONAL GAGANG KAYU', category: '🧹 Alat Kebersihan Menyapu Lantai Rumah', theme: 'ALAM' },
  { civilian: 'DISPENSER AIR GALON DINGIN PANAS', undercover: 'TEKO CERET REBUS AIR PANAS', category: '🚰 Penyedia Pasokan Air Minum Bersih Rumah', theme: 'ALAM' },
  { civilian: 'SPEAKER BLUETOOTH BASS PORTABEL', undercover: 'HEADPHONE OVER-EAR KEDAP SUARA', category: '🔊 Perangkat Output Audio Suara Musik', theme: 'ALAM' },

  // Destinasi, Tempat & Pariwisata
  { civilian: 'PANTAI PASIR PUTIH OMBAK LAUT', undercover: 'PUNCAK GUNUNG KABUT DINGIN HIJAU', category: '🏞️ Destinasi Liburan Alam Terbuka Favorit', theme: 'ALAM' },
  { civilian: 'CANDI BOROBUDUR MEGAH MAGELANG', undercover: 'CANDI PRAMBANAN TINGGI YOGYAKARTA', category: '🏛️ Situs Wisata Cagar Budaya Bersejarah Bangsa', theme: 'ALAM' },
  { civilian: 'DANAU TOBA SUMATERA UTARA', undercover: 'KAWAH PUTIH GUNUNG PATUHA CIWIDEY', category: '🌋 Wisata Danau Alam Vulkanik Eksotis', theme: 'ALAM' },
  { civilian: 'PULAU DEWATA BALI KUTA SANUR', undercover: 'KEPULAUAN RAJA AMPAT PAPUA BARAT', category: '🏝️ Destinasi Wisata Bahari Kelas Dunia', theme: 'ALAM' },
  { civilian: 'AIR TERJUN CURUG ALAM SEGAR', undercover: 'SUNGAI ARUNG JERAM BATU DERAS', category: '🌊 Wisata Alam Petualangan Air Mengalir', theme: 'ALAM' },
  { civilian: 'TAMAN SAFARI INDONESIA KELILING MOBIL', undercover: 'KEBUN BINATANG RAGUNAN JALAN KAKI', category: '🦁 Tempat Wisata Rekreasi Konservasi Satwa', theme: 'ALAM' },
  { civilian: 'MUSEUM NASIONAL GAJAH SEJARAH', undercover: 'GALERI SENI AESTHETIC CONTEMPORARY', category: '🖼️ Tempat Edukasi Pameran Benda Seni Budaya', theme: 'ALAM' },
  { civilian: 'HOTEL BINTANG LIMA RESORT MEWAH', undercover: 'VILLA PEGUNUNGAN KOLAM RENANG PRIVAT', category: '🏨 Fasilitas Penginapan Liburan Nyaman Keluarga', theme: 'ALAM' },
  { civilian: 'BANDARA UDARA INTERNASIONAL PESAWAT', undercover: 'STASIUN KERETA API REL JALUR KAI', category: '✈️ Pintu Keberangkatan Transportasi Moda Publik', theme: 'ALAM' },
  { civilian: 'PELABUHAN LAUT KAPAL FERRY DERMAGA', undercover: 'TERMINAL BUS ANTAR KOTA PROVINSI', category: '🚢 Tempat Titik Kumpul Penumpang Bepergian', theme: 'ALAM' },
  { civilian: 'MALL PERBELANJAAN MEGAH PUSAT KOTA', undercover: 'PASAR TRADISIONAL SUBUH TAWAR MENAWAR', category: '🛒 Tempat Transaksi Jual Beli Kebutuhan Belanja', theme: 'ALAM' },
  { civilian: 'STADION UTAMA GELORA BUNG KARNO (GBK)', undercover: 'GELANGGANG OLAHRAGA (GOR) BULUTANGKIS', category: '🏟️ Kompleks Arena Pertandingan Olahraga Akbar', theme: 'ALAM' },
  { civilian: 'RUMAH SAKIT UMUM PUSAT (RSUP)', undercover: 'PUSKESMAS KELURAHAN PELAYANAN MEDIS', category: '🏥 Fasilitas Gedung Pusat Pelayanan Kesehatan Warga', theme: 'ALAM' },
  { civilian: 'MARKAS KANTOR POLISI POLRES', undercover: 'POS RONDA KAMPUNG SISKAMLING MALAM', category: '👮 Tempat Penjagaan Keamanan & Ketertiban Umum', theme: 'ALAM' },

  // Pakaian, Aksesoris & Barang Pribadi
  { civilian: 'DOMPET KULIT ASLI LIPAT KARTU', undercover: 'TAS RANSEL PUNGGUNG LAPTOP GENDONG', category: '🎒 Wadah Tempat Membawa Barang Bawaan Pribadi', theme: 'ALAM' },
  { civilian: 'KACAMATA HITAM POLARIZED ANTI SILAU', undercover: 'KACAMATA MINUS LENSA BACA OPTIK', category: '👓 Alat Aksesoris Pelindung & Pembantu Mata', theme: 'ALAM' },
  { civilian: 'SEPATU SNEAKERS CASUAL RUNNING', undercover: 'SEPATU PANTOFEL KULIT FORMAL KANTOR', category: '👟 Perlengkapan Alas Kaki Berjalan Kaki', theme: 'ALAM' },
  { civilian: 'SANDAL JEPIT SWALLOW KARET HIJAU', undercover: 'SANDAL SLOP KULIT SLOP KASUAL', category: '🩴 Alas Kaki Santai Untuk Bepergian Dekat', theme: 'ALAM' },
  { civilian: 'JAKET HOODIE HANGAT PENUTUP KEPALA', undercover: 'SWEATER RAJUT BULU TEBAL MUSIM DINGIN', category: '🧥 Pakaian Luar Busana Pelindung Dari Suhu Dingin', theme: 'ALAM' },
  { civilian: 'CELANA JEANS DENIM BIRU KLASIK', undercover: 'CELANA CHINO KAIN KANTOR RAPI', category: '👖 Pakaian Bawahan Celana Panjang Pria Wanita', theme: 'ALAM' },
  { civilian: 'KAOS OBLONG POLOS KATUN COMBED', undercover: 'KEMEJA BATIK LENGAN PANJANG RESMI', category: '👔 Busana Pakaian Atasan Sehari-hari & Acara', theme: 'ALAM' },
  { civilian: 'TOPI BASEBALL LIDAH LENGKUNG', undercover: 'TOPI KUPLUK RAJUT WOL HANGAT BEANIE', category: '🧢 Penutup Kepala Pelindung Matahari & Gaya', theme: 'ALAM' },
  { civilian: 'PARFUM EAU DE PARFUM WANGI TAHAN LAMA', undercover: 'DEODORANT ROLL ON PENCEGAH BAU BADAN', category: '🧴 Produk Perawatan Wewangian Tubuh Bersih', theme: 'ALAM' },
  { civilian: 'SABUN MANDI BATANG WANGI BUSA', undercover: 'SHAMPO RAMBUT ANTI KETOMBE BOTOL', category: '🧼 Perlengkapan Sabun Mandi Pembersih Badan', theme: 'ALAM' },
  { civilian: 'SIKAT GIGI BULU LEMBUT GAGANG', undercover: 'PASTA GIGI ODOL MINT SEGAR GIGI', category: '🪥 Perlengkapan Pembersih Mulut & Gigi Putih', theme: 'ALAM' },
  { civilian: 'GUNTING KUKU BAJA STAINLESS TANGAN', undercover: 'SISIR RAMBUT GIGI RAPAT PENATA', category: '✂️ Peralatan Kecil Perawatan Tubuh & Rambut', theme: 'ALAM' },
  { civilian: 'BANTAL KAPUK EMPUK KEPALA TIDUR', undercover: 'GULING PANJANG EMPUK PELUK NYENYAK', category: '🛏️ Perlengkapan Tempat Tidur Teman Istirahat Kasur', theme: 'ALAM' },
  { civilian: 'SELIMUT BULU HANGAT LEMBUT TIDUR', undercover: 'SPREI SUTRA KARET SISI KASUR RANJANG', category: '🛌 Perlengkapan Penutup Kasur Kamar Tidur Nyaman', theme: 'ALAM' },
  { civilian: 'GELANG EMAS MURNI KADAR 24 KARAT', undercover: 'CINCIN PERAK BATU PERMATA BERLIAN', category: '💍 Perhiasan Mewah Aksesoris Berharga Bernilai Tinggi', theme: 'ALAM' },
  { civilian: 'KALUNG MUTIARA AIR LAUT ELEGAN', undercover: 'ANTING GIWANG EMAS PUTIH TELINGA', category: '💎 Aksesoris Perhiasan Cantik Wanita Menawan', theme: 'ALAM' },
  { civilian: 'GUNTING KERTAS KANTOR GAGANG PLASTIK', undercover: 'CUTTER PISAU TAJAM BLADE BONGKAR', category: '✂️ Alat Kantor Pemotong Kertas & Paket Kardus', theme: 'ALAM' },
  { civilian: 'PENSIL KAYU 2B UJIAN KOMPUTER', undercover: 'PULPEN GEL TINTA HITAM TULIS TANGAN', category: '✏️ Alat Tulis Menulis Kebutuhan Sekolah & Kantor', theme: 'ALAM' },
  { civilian: 'BUKU TULIS CATATAN BERGARIS BUKU', undercover: 'KERTAS HVS A4 PUTIH 80 GRAM CETAK PRINT', category: '📓 Media Lembaran Kertas Tulis Menulis & Cetak Dokumen', theme: 'ALAM' }
];
